### ISSUE TITLE
Error 'google is not defined'

### ISSUE THREAD

**Issue by Rick49** [Jam3/extract-streetview#10]
I installed extract-streetview with npm, and ran the following command with the results shown:

C:\Users\rick1>extract-streetview 36.1517908,-114.5641652,17 > Downloads\panorama.jpg

ReferenceError: google is not defined
    at extract (C:\Users\rick1\AppData\Roaming\npm\node_modules\extract-streetview\index.js:83:9)
    at parseLocation.then.location (C:\Users\rick1\AppData\Roaming\npm\node_modules\extract-streetview\index.js:35:21)

**Comment by saedrna** [comment]
same problem on windows. Mac is OK.

**Comment by kubriel** [comment]
same here on linux
