### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by aziz** [Jam3/extract-streetview#3]
`extract-streetview [REMOVED] --zoom 4 > panorama.png`

```
module.js:341
    throw err;
    ^

Error: Cannot find module 'devtool/bin/spawn'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/allen/.npm-packages/lib/node_modules/extract-streetview/cmd.js:7:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
```

**Comment by mattdesl** [comment]
Fixed in `1.1.0`. To update:

``` sh
npm install extract-streetview -g
```

Thanks for the report! :smile:
